name: Get OpenAI API Key

on:
  push:
    branches:
      - main  # Chạy workflow khi có push lên nhánh main
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request vào nhánh main

jobs:
  get-api-key:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout code của bạn

      - name: Get OpenAI API Key from GitHub Secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Lấy API key từ Secrets
        run: |
          echo "OpenAI API Key has been retrieved."
          echo "The OpenAI API Key is: $OPENAI_API_KEY"
