name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Triển khai khi có push vào nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV  # Đặt OPENAI_API_KEY trong môi trường

    - name: Verify environment variable
      run: |
        echo "OPENAI_API_KEY is set to $OPENAI_API_KEY"  # In ra giá trị của OPENAI_API_KEY
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Truyền biến môi trường vào env cho bước này
